version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    container_name: mongo-rest
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  go-app:
    build: .
    depends_on:
      - mongo_db
    env_file:
      - .env
    environment:
      PORT: 3030
      MONGO_URI: "mongodb://mongo_db:27017"
      DATABASE: "mongo_go"
    ports:
      - 3030:3030
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0

volumes:
  mongo_db: {}